---
replicas: 1

image:
  repository: quay.io/eformat/maas-tokenizer
  tag: latest
  pullPolicy: Always

maasUrl: ""
maasToken: ""
tokenExpiry: "24h"
reconcileFrequency: "10m"

serviceAccount:
  create: true
  name: ""

extraTokens:
  stt-token: ""
